variables:
  CI_IMAGE_TAG: 'cuda'
  JULIA_NUM_THREADS: '4'

include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/common.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/test_v1.0.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/test_v1.1.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/test_v1.2.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/test_v1.3.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/test_dev.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/coverage_v1.2.yml'
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v4/documentation_v1.2.yml'

test:v1.3:
  allow_failure: true

test:dev:
  allow_failure: true

pages:
  stage: deploy
  script:
    - mv docs/build public
  artifacts:
    paths:
    - public
  only:
    - master

test:v1.2-split:
  extends: .test
  variables:
    CI_VERSION_TAG: 'v1.2'
    CUARRAYS_MEMORY_POOL: 'split'

flux:
  stage: test
  image: "juliagpu/julia:v1.2-cuda"
  script:
    - mkdir $JULIA_DEPOT_PATH # Pkg.jl#325
    - julia -e 'using Pkg;
                Pkg.develop([PackageSpec(path=pwd());
                             [PackageSpec(name=pkg)
                              for pkg in split(get(ENV,"CI_DEV_PKGS",""))]]);
                Pkg.build("CuArrays")'
    - julia -e 'using Pkg;
                Pkg.add("Flux");
                Pkg.test("Flux")'
  allow_failure: true
